# 初始化
/run/initialize

# 输出控制
/control/verbose 1
/run/verbose 1
/tracking/verbose 0
# 关闭光学相关日志
/optical/verbose 0
/process/optical/verbose 0
/process/scintillation/verbose 0
/process/cerenkov/verbose 0
/process/wls/verbose 0

# 定义粒子源（中子）
/gps/particle gamma 

# 设置源的几何形状（圆柱体）
/gps/position 0 3.1 0 cm  # 中心坐标

# 设置粒子方向为各向同性
/gps/ang/type iso

# 设置能量为 1.35 MeV 单能谱
/gps/ene/type Arb
/gps/hist/type arb

/gps/hist/point 1.17  0.7   
/gps/hist/point 1.33 1

/gps/hist/inter Lin

/run/beamOn 10000 

